sudo: required
services:
  - docker

scripts:
  - docker build -t degank/node .
  - docker images degank/node

before_deploy:
  - docker login -u degank -p dkDocker!m@n

deploy:
  provider: script
  script: docker push degank/node
  on:
    branch: master
